# Generated by Django 5.2.4 on 2025-07-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Approvals',
            new_name='Approval',
        ),
    ]
